# Generated by Django 4.2.17 on 2024-12-30 12:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='kowt6jue5wdyjqwk29jk', max_length=255, null=True, verbose_name='Profile Picture'),
        ),
    ]
