# Generated by Django 4.2.17 on 2024-12-30 12:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pictures/placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
