# Generated by Django 4.2.17 on 2024-12-24 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("features", models.TextField(blank=True, null=True)),
                ("injury_condition", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="InjuryReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="Open",
                        max_length=15,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Provide a specific title for the report (e.g., 'Cat injured on left paw').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Provide a detailed description of the situation."
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[("Cat", "Cat"), ("Dog", "Dog"), ("Other", "Other")],
                        help_text="Select the species of the animal.",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Unknown", "Unknown"),
                        ],
                        help_text="Select the gender of the animal if known.",
                        max_length=50,
                    ),
                ),
                (
                    "injury_condition",
                    models.CharField(
                        choices=[
                            ("Slightly Injured", "Slightly Injured"),
                            ("Seriously Injured", "Seriously Injured"),
                            ("Not Injured", "Not Injured"),
                        ],
                        help_text="Describe the severity of the injury.",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Enter the nearest city or coordinates.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a clear image if possible.",
                        null=True,
                        upload_to="injury_reports/",
                    ),
                ),
                ("date_reported", models.DateTimeField(auto_now_add=True)),
                ("admin_comment", models.TextField(blank=True, null=True)),
                (
                    "edit_history",
                    models.TextField(
                        blank=True,
                        help_text="Track changes made to the report.",
                        null=True,
                    ),
                ),
                (
                    "helper",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who is taking care of this report.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="helper",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "helpers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="helped_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
