# Generated by Django 4.2.17 on 2025-02-24 09:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryreport',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a clear image if possible.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
