# Generated by Django 4.2.17 on 2025-03-11 11:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_injuryreport_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryreport',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='injury_reports/placeholder_report', help_text='Upload a clear image if possible.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
