# Generated by Django 4.2.17 on 2024-12-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_remove_injuryreport_animal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injuryreport",
            name="description",
            field=models.TextField(
                help_text="Provide a detailed description of the situation."
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Unknown", "Unknown"),
                ],
                help_text="Select the gender of the animal if known.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a clear image if possible.",
                null=True,
                upload_to="injury_reports/",
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="injury_condition",
            field=models.CharField(
                choices=[
                    ("Slightly Injured", "Slightly Injured"),
                    ("Seriously Injured", "Seriously Injured"),
                    ("Not Injured", "Not Injured"),
                ],
                help_text="Describe the severity of the injury.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Enter the nearest city or coordinates.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="species",
            field=models.CharField(
                choices=[("Cat", "Cat"), ("Dog", "Dog"), ("Other", "Other")],
                help_text="Select the species of the animal.",
                max_length=50,
            ),
        ),
    ]
