# Generated by Django 4.2.17 on 2024-12-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_injuryreport_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuryreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
