# Generated by Django 4.2.17 on 2024-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_injuryreport_admin_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuryreport",
            name="title",
            field=models.CharField(
                default="Default Title",
                help_text="Provide a specific title for the report (e.g., 'Cat injured on left paw').",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
