# Generated by Django 4.2.17 on 2024-12-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0007_injuryreport_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuryreport",
            name="edit_history",
            field=models.TextField(
                blank=True, help_text="Track changes made to the report.", null=True
            ),
        ),
    ]
