# Generated by Django 4.2.17 on 2024-12-16 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0008_injuryreport_edit_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuryreport",
            name="helper",
            field=models.ForeignKey(
                blank=True,
                help_text="User who is taking care of this report.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="helper",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
