# Generated by Django 4.2.17 on 2024-12-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0009_injuryreport_helper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injuryreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
