# Generated by Django 4.2.17 on 2024-12-18 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0012_alter_injuryreport_publication_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuryreport",
            name="helpers",
            field=models.ManyToManyField(
                blank=True, related_name="helped_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="injuryreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Open",
                max_length=15,
            ),
        ),
    ]
